# Generated by Django 4.1.1 on 2022-09-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission', models.CharField(max_length=200)),
                ('dept', models.CharField(max_length=100)),
                ('seat', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=10)),
                ('vote', models.IntegerField(default=0)),
            ],
        ),
    ]
